name: Daily GitHub Trending

on:
  schedule:
    # Daily at 21:30 (+8:00 UTC)
    - cron: "30 13 * * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  run-daily-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Send Daily GitHub Trending to Telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python -c "import os; from src.bot.telegram_bot import GithubTrendingBot; bot = GithubTrendingBot(os.getenv('TELEGRAM_TOKEN')); import asyncio; asyncio.run(bot.send_trending_to_telegram(period='daily'))"
