name: Daily Job Scheduler

on:
  schedule:
    # Daily at 21:00 UTC
    - cron: "0 21 * * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  run-daily-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run daily fetch and save
      run: |
        python -c "from src.services.fetch_service import fetch_and_save_repos; fetch_and_save_repos('daily')"
