name: Monthly GitHub Trending

on:
  schedule:
    # Weekly on Monday at 18:00 (+8:00 UTC)
    - cron: "0 10 * * 1"
  # Manual trigger
  workflow_dispatch:

jobs:
  run-monthly-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Send Monthly GitHub Trending to Telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python -c "
import os
from src.bot.telegram_bot import GithubTrendingBot
bot = GithubTrendingBot(os.getenv('TELEGRAM_TOKEN'))
await bot.handle_trending(period='monthly')"
